- name: create elastic load balancer
  hosts: localhost
  connection: local
  tasks:
    -name: elb_loadbal
     ec2_elb_lb:
       name: 
       state:
       region:
       cross_az_load_balancing: 
       listeners:
         - protocol: http
           load_balancer_port: 80
           instance_port: 80
       tags:
         name: ravitzelb
       security_group_ids:
       zones: 
